// -------------------------------------------------------------------------------
// THIS FILE IS ORIGINALLY GENERATED BY THE DESIGNER.
// YOU ARE ONLY ALLOWED TO MODIFY CODE BETWEEN '///<<< BEGIN' AND '///<<< END'.
// PLEASE MODIFY AND REGENERETE IT IN THE DESIGNER FOR CLASS/MEMBERS/METHODS, ETC.
// -------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

///<<< BEGIN WRITING YOUR CODE FILE_INIT

///<<< END WRITING YOUR CODE

public class RobotAgent : behaviac.Agent
///<<< BEGIN WRITING YOUR CODE RobotAgent
///<<< END WRITING YOUR CODE
{
	public static uint AgentCount = 0;

	public static bool ForceLogout = false;

	public bool IsLogin = false;

	public static bool IsShowLogMessage = true;

	public bool IsTryLogin = false;

	public uint LoginTimes = 0;

	public static uint PassTestCount = 0;

	public string Password = "123456";

	public long TempLong1 = 0;

	public long TempLong2 = 0;

	public string TempString1 = "";

	public string TempString2 = "";

	public string Username = "liu";

	public void AddBlackFriend(string param0)
	{
///<<< BEGIN WRITING YOUR CODE AddBlackFriend
///<<< END WRITING YOUR CODE
	}

	public void AddFriend(long param0)
	{
///<<< BEGIN WRITING YOUR CODE AddFriend
///<<< END WRITING YOUR CODE
	}

	public void AddGoal(uint param0)
	{
///<<< BEGIN WRITING YOUR CODE AddGoal
///<<< END WRITING YOUR CODE
	}

	public void AgentLog(string param0)
	{
///<<< BEGIN WRITING YOUR CODE AgentLog
///<<< END WRITING YOUR CODE
	}

	public void BuyItem(uint param0, sbyte param1, int param2)
	{
///<<< BEGIN WRITING YOUR CODE BuyItem
///<<< END WRITING YOUR CODE
	}

	public void ChatTo(long param0, string param1)
	{
///<<< BEGIN WRITING YOUR CODE ChatTo
///<<< END WRITING YOUR CODE
	}

	public void DelBlackFriend(string param0)
	{
///<<< BEGIN WRITING YOUR CODE DelBlackFriend
///<<< END WRITING YOUR CODE
	}

	public void DelFriend(long param0)
	{
///<<< BEGIN WRITING YOUR CODE DelFriend
///<<< END WRITING YOUR CODE
	}

	public void DelGoal(uint param0)
	{
///<<< BEGIN WRITING YOUR CODE DelGoal
///<<< END WRITING YOUR CODE
	}

	public static string Format1(string param0, long param1)
	{
///<<< BEGIN WRITING YOUR CODE Format1
		return "";
///<<< END WRITING YOUR CODE
	}

	public static string Format2(string param0, long param1, long param2)
	{
///<<< BEGIN WRITING YOUR CODE Format2
///<<< END WRITING YOUR CODE
	}

	public long GetDianQuan()
	{
///<<< BEGIN WRITING YOUR CODE GetDianQuan
		return 0;
///<<< END WRITING YOUR CODE
	}

	public string GetGUIDString()
	{
///<<< BEGIN WRITING YOUR CODE GetGUIDString
		return "";
///<<< END WRITING YOUR CODE
	}

	public long GetJinBi()
	{
///<<< BEGIN WRITING YOUR CODE GetJinBi
		return 0;
///<<< END WRITING YOUR CODE
	}

	public long GetLastOnlineTime1970()
	{
///<<< BEGIN WRITING YOUR CODE GetLastOnlineTime1970
		return 0;
///<<< END WRITING YOUR CODE
	}

	public short GetLevel()
	{
///<<< BEGIN WRITING YOUR CODE GetLevel
		return 0;
///<<< END WRITING YOUR CODE
	}

	public long GetLoginCount()
	{
///<<< BEGIN WRITING YOUR CODE GetLoginCount
		return 0;
///<<< END WRITING YOUR CODE
	}

	public static uint GetLoginedUserCount()
	{
///<<< BEGIN WRITING YOUR CODE GetLoginedUserCount
///<<< END WRITING YOUR CODE
	}

	public string GetNameAlias()
	{
///<<< BEGIN WRITING YOUR CODE GetNameAlias
		return "";
///<<< END WRITING YOUR CODE
	}

	public static uint GetNetAgentCount()
	{
///<<< BEGIN WRITING YOUR CODE GetNetAgentCount
		return 0;
///<<< END WRITING YOUR CODE
	}

	public static uint GetProcessID()
	{
///<<< BEGIN WRITING YOUR CODE GetProcessID
		return 0;
///<<< END WRITING YOUR CODE
	}

	public static int GetRandomInt(int param0, int param1)
	{
///<<< BEGIN WRITING YOUR CODE GetRandomInt
		return 0;
///<<< END WRITING YOUR CODE
	}

	public static long GetRandomLong(long param0, long param1)
	{
///<<< BEGIN WRITING YOUR CODE GetRandomLong
		return 0;
///<<< END WRITING YOUR CODE
	}

	public long GetVIPEndTime()
	{
///<<< BEGIN WRITING YOUR CODE GetVIPEndTime
		return 0;
///<<< END WRITING YOUR CODE
	}

	public short GetVIPLevel()
	{
///<<< BEGIN WRITING YOUR CODE GetVIPLevel
		return 0;
///<<< END WRITING YOUR CODE
	}

	public long GetZuanShi()
	{
///<<< BEGIN WRITING YOUR CODE GetZuanShi
		return 0;
///<<< END WRITING YOUR CODE
	}

	public bool HasHero(uint param0)
	{
///<<< BEGIN WRITING YOUR CODE HasHero
		return 0;
///<<< END WRITING YOUR CODE
	}

	public bool HasItem(uint param0)
	{
///<<< BEGIN WRITING YOUR CODE HasItem
		return 0;
///<<< END WRITING YOUR CODE
	}

	public bool HasSkin(uint param0)
	{
///<<< BEGIN WRITING YOUR CODE HasSkin
		return false;
///<<< END WRITING YOUR CODE
	}

	public void Login(uint param0)
	{
///<<< BEGIN WRITING YOUR CODE Login
///<<< END WRITING YOUR CODE
	}

	public void Logout()
	{
///<<< BEGIN WRITING YOUR CODE Logout
///<<< END WRITING YOUR CODE
	}

	public void ModDianQuan(int param0)
	{
///<<< BEGIN WRITING YOUR CODE ModDianQuan
///<<< END WRITING YOUR CODE
	}

	public void ModJinBi(int param0)
	{
///<<< BEGIN WRITING YOUR CODE ModJinBi
///<<< END WRITING YOUR CODE
	}

	public void ModZuanShi(int param0)
	{
///<<< BEGIN WRITING YOUR CODE ModZuanShi
///<<< END WRITING YOUR CODE
	}

	public void SellItem(uint param0, int param1)
	{
///<<< BEGIN WRITING YOUR CODE SellItem
///<<< END WRITING YOUR CODE
	}

	public void SendMail(string param0, string param1, string param2)
	{
///<<< BEGIN WRITING YOUR CODE SendMail
///<<< END WRITING YOUR CODE
	}

	public void SetFriendNote(long param0, string param1)
	{
///<<< BEGIN WRITING YOUR CODE SetFriendNote
///<<< END WRITING YOUR CODE
	}

///<<< BEGIN WRITING YOUR CODE CLASS_PART

///<<< END WRITING YOUR CODE

}

///<<< BEGIN WRITING YOUR CODE FILE_UNINIT

///<<< END WRITING YOUR CODE

